name: Sponsors Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sponsors
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.x

      - run: npx pnpm i

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.KASHALLS_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: kashalls

      - name: Commit
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          message: "chore: update sponsors.svg"
          add: "./sponsors/sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.KASHALLS_TOKEN }}